(function(){
'use strict';
const OWNER='ankitvrsharma',REPO='ankitvrsharma/NET-Psychology',BRANCH='main',KEY='netPsychAdminToken',AUTH='netPsychAdminAuthenticated';
const root=document.querySelector('#adminApp'),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let token=sessionStorage.getItem(KEY)||'',auditState={schema_version:2,owner_review:{microtopics:{},questions:{}},updated_at:''},data=null,questions=[],filter='NEED REVIEW';
const api=async(path,options={})=>{const r=await fetch('https://api.github.com'+path,{...options,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})}});if(!r.ok)throw new Error('GitHub API '+r.status);return r.json()};
const loadJSON=async(path)=>{const r=await fetch('./'+path+'?v=20261006-audit-static-pools',{cache:'no-store'});if(!r.ok)throw new Error(path+' '+r.status);return r.json()};
const review=(type,id)=>String(auditState.owner_review?.[type]?.[String(id)]||'');
const hasContent=m=>{const values=[m.expert_explanation,m.detailed_explanation,m.deep_learning,m.deep,m.content_notes,m.study_notes,m.application_question,m.recall_cue,m.memory_hook,m.exam_takeaway];const text=values.map(v=>Array.isArray(v)?v.map(x=>typeof x==='object'&&x?JSON.stringify(x):String(x||'')).join(' '):v&&typeof v==='object'?JSON.stringify(v):String(v||'')).join(' ').replace(/\s+/g,' ').trim();return text.length>=80};
async function loadAuditState(){const r=await fetch('./content-audit.json?v=20261006-audit-static-pools',{cache:'no-store'});if(r.ok)auditState=await r.json();if(!auditState.owner_review)auditState.owner_review={microtopics:{},questions:{}}}
function buildAdminData(syllabus,microPool){return {...syllabus,units:(syllabus.units||[]).map(u=>({...u,topics:(u.topics||[]).map(t=>({...t,microtopics:(t.microtopics||[]).map(ref=>microPool[String(u.id)+'-'+String(t.id)+'-'+String(ref.id)]||ref)}))}))};}
function loginView(message=''){root.innerHTML='<section class="admin-auth card"><div class="eyebrow">OWNER AUDIT</div><h1>Content Audit Workbench</h1><p>Review failed content, record your expert judgement, and keep learner-facing verification labels separate from internal review data.</p><label class="admin-field"><span>GitHub token</span><input id="adminToken" type="password" autocomplete="off" placeholder="github_pat_…"></label><button class="btn primary" id="adminLogin">SIGN IN →</button><p class="admin-help">The GitHub account must be <b>ankitvrsharma</b> and the token needs repository Contents read/write access.</p>'+(message?'<div class="admin-error" role="alert">'+esc(message)+'</div>':'')+'</section>';document.querySelector('#adminLogin').onclick=login}
async function login(){const input=document.querySelector('#adminToken'),v=input?.value.trim();if(!v)return loginView('Enter your GitHub token.');token=v;try{const me=await api('/user');if(me.login!==OWNER)throw new Error('This GitHub account is not the site owner.');sessionStorage.setItem(KEY,token);sessionStorage.setItem(AUTH,'1');await dashboard()}catch(e){sessionStorage.removeItem(KEY);token='';loginView(e.message||'Sign-in failed.');}}
function titleFor(type,id){if(type==='microtopics'){const [u,t,m]=String(id).split('-').map(Number),unit=data?.units?.find(x=>x.id===u),topic=unit?.topics?.find(x=>x.id===t),micro=topic?.microtopics?.find(x=>x.id===m);return micro?unit.title+' · '+topic.title+' · '+micro.title:id}const q=questions.find(x=>String(x.id)===String(id));return q?.question||id}
function hrefFor(type,id){if(type==='microtopics'){const [u,t,m]=String(id).split('-');return 'microtopic.html?unit='+encodeURIComponent(u)+'&topic='+encodeURIComponent(t)+'&micro='+encodeURIComponent(m)}return 'practice.html'}
function makeItem(type,id,audit){const owner=review(type,id),ownerLabel=owner?'<span class="review-status '+owner.toLowerCase().replace(/_/g,'-')+'">'+esc(owner.replace(/_/g,' '))+'</span>':'';const actions=owner?'<button class="btn admin-clear" data-type="'+type+'" data-id="'+esc(id)+'">CLEAR OWNER REVIEW</button>':'<button class="btn primary admin-review" data-review="SATISFACTORY" data-type="'+type+'" data-id="'+esc(id)+'">MARK SATISFACTORY</button><button class="btn admin-review" data-review="NOT_SATISFACTORY" data-type="'+type+'" data-id="'+esc(id)+'">MARK NOT SATISFACTORY</button>';const auto=audit.status==='PASS'?'VERIFIED':'NO LEARNER TAG';return '<article class="admin-item"><div class="admin-item-copy">'+ownerLabel+'<span class="admin-status '+String(audit.status).toLowerCase()+'">'+esc(audit.status)+'</span><h3>'+esc(titleFor(type,id))+'</h3><p>Audit score: <b>'+audit.score+'</b> · '+esc((audit.issues||[]).join(', ')||'No audit issues')+' · Learner tag: <b>'+auto+'</b></p></div><div class="admin-actions"><a class="btn" href="'+hrefFor(type,id)+'">OPEN</a>'+actions+'</div></article>'}
function rowsFor(selectedFilter='ALL'){const ctx={get data(){return data},get questions(){return questions}},audit=window.NETPsychologyContentAudit.create(ctx).expertAudit;const micros=(data?.units||[]).flatMap(u=>(u.topics||[]).flatMap(t=>(t.microtopics||[]).filter(hasContent).map(m=>({type:'microtopics',id:String(u.id)+'-'+String(t.id)+'-'+String(m.id)}))));const qs=questions.map(q=>({type:'questions',id:String(q.id)}));const rows=[...micros,...qs].map(x=>{const a=audit(x.type,x.id),r=review(x.type,x.id);return{x,a,st:r||a.status}});return rows.filter(r=>selectedFilter==='ALL'||(selectedFilter==='NEED REVIEW'?r.a.status!=='PASS'&&r.st==='':selectedFilter===r.st)).sort((a,b)=>a.a.score-b.a.score)}
function renderQueue(){const allRows=rowsFor('ALL'),visible=rowsFor(filter),need=allRows.filter(r=>r.a.status!=='PASS'&&r.st==='').length,sat=allRows.filter(r=>r.st==='SATISFACTORY').length,unsat=allRows.filter(r=>r.st==='NOT_SATISFACTORY').length;root.querySelector('#adminQueue').innerHTML='<section class="admin-toolbar card"><div><strong>'+allRows.length+'</strong><span>content items</span></div><div><strong>'+need+'</strong><span>need owner review</span></div><div><strong>'+sat+'</strong><span>satisfactory</span></div><div><strong>'+unsat+'</strong><span>not satisfactory</span></div><button class="btn" id="adminLogout">SIGN OUT</button></section><div class="admin-filters">'+['ALL','NEED REVIEW','SATISFACTORY','NOT_SATISFACTORY'].map(x=>'<button class="admin-filter '+(filter===x?'active':'')+'" data-filter="'+x+'">'+x.replace(/_/g,' ')+'</button>').join('')+'</div>'+(visible.length?visible.map(r=>makeItem(r.x.type,r.x.id,r.a)).join(''):'<section class="card admin-empty"><h2>No items in this view</h2><p>Change the filter to see another review state.</p></section>');root.querySelector('#adminLogout').onclick=logout;root.querySelectorAll('.admin-filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderQueue()});root.querySelectorAll('.admin-review').forEach(b=>b.onclick=()=>changeReview(b.dataset.type,b.dataset.id,b.dataset.review));root.querySelectorAll('.admin-clear').forEach(b=>b.onclick=()=>changeReview(b.dataset.type,b.dataset.id,''))}
async function changeReview(type,id,value){auditState.owner_review[type]=auditState.owner_review[type]||{};if(value)auditState.owner_review[type][String(id)]=value;else delete auditState.owner_review[type][String(id)];auditState.updated_at=new Date().toISOString();try{const file=await api('/repos/'+REPO+'/contents/content-audit.json?ref='+encodeURIComponent(BRANCH));const body=btoa(unescape(encodeURIComponent(JSON.stringify(auditState,null,2)+'\n')));await api('/repos/'+REPO+'/contents/content-audit.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Admin: '+(value?'mark '+value.toLowerCase().replace(/_/g,' '):'clear owner review')+' '+type+' '+id,content:body,sha:file.sha,branch:BRANCH})});await loadAuditState();renderQueue()}catch(e){alert('Could not save the review status: '+e.message)}}
async function checkSite(){const checks=await Promise.all(['./index.html','./app/runtime.js','./style.css','./data/syllabus-index.json','./content/microtopics/micro_topics.json','./content/questions/questions.json'].map(async path=>{try{const r=await fetch(path+'?health='+Date.now(),{cache:'no-store'});return r.ok}catch{return false}}));return checks.every(Boolean)}
function logout(){sessionStorage.removeItem(KEY);sessionStorage.removeItem(AUTH);token='';loginView()}
async function dashboard(){root.innerHTML='<section class="admin-hero"><div class="eyebrow">OWNER AUDIT</div><h1>Content Audit Workbench</h1><p>System-passed content receives <b>VERIFIED</b>. Content you mark <b>NOT SATISFACTORY</b> receives <b>EXPERT VERIFIED</b>. Other learner-facing content receives no verification tag.</p></section><div id="adminQueue" class="admin-queue"><div class="card">Loading content…</div></div>';try{const [syllabus,microPool,qpool]=await Promise.all([loadJSON('data/syllabus-index.json'),loadJSON('content/microtopics/micro_topics.json'),loadJSON('content/questions/questions.json'),loadAuditState()]);data=buildAdminData(syllabus,microPool);questions=Array.isArray(qpool)?qpool:[...(Array.isArray(qpool?.pyq)?qpool.pyq:[]),...(Array.isArray(qpool?.practice)?qpool.practice:[])];const running=await checkSite();root.querySelector('#adminQueue').insertAdjacentHTML('afterbegin','<section class="card admin-health"><div><div class="eyebrow">WEBSITE STATUS</div><strong>'+ (running?'RUNNING':'CHECK FAILED') +'</strong><p>Core pages, runtime, stylesheet and published content pools '+(running?'are responding.':'did not all respond.')+'</p></div></section>');renderQueue()}catch(e){root.innerHTML='<section class="card"><h2>Could not load audit data</h2><p>'+esc(e.message)+'</p><button class="btn" id="adminLogout">SIGN OUT</button></section>';document.querySelector('#adminLogout').onclick=logout}}
async function start(){if(!token)return loginView();try{const me=await api('/user');if(me.login!==OWNER)throw new Error('Owner account required.');await dashboard()}catch(e){logout()}}
start();
})();