(function(){
'use strict';
const OWNER='ankitvrsharma',REPO='ankitvrsharma/NET-Psychology',BRANCH='main',KEY='netPsychAdminToken',AUTH='netPsychAdminAuthenticated';
const root=document.querySelector('#adminApp'),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let token=sessionStorage.getItem(KEY)||'',auditState={schema_version:1,expert_reviewed:{microtopics:[],questions:[]},updated_at:''},data=null,questions=[],filter='NEED REVIEW';
const api=async(path,options={})=>{const r=await fetch('https://api.github.com'+path,{...options,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})}});if(!r.ok)throw new Error('GitHub API '+r.status);return r.json()};
const loadJSON=async(path)=>{const r=await fetch('./'+path+'?v=20261006-audit-status-v1',{cache:'no-store'});if(!r.ok)throw new Error(path+' '+r.status);return r.json()};
const ids=type=>Array.isArray(auditState.expert_reviewed?.[type])?auditState.expert_reviewed[type].map(String):[];
const status=(type,id,audit)=>ids(type).includes(String(id))?'EXPERT REVIEWED':audit.status==='PASS'?'REVIEWED':'NEED REVIEW';
const hasContent=m=>{const values=[m.expert_explanation,m.detailed_explanation,m.deep_learning,m.deep,m.content_notes,m.study_notes,m.application_question,m.recall_cue,m.memory_hook,m.exam_takeaway];const text=values.map(v=>Array.isArray(v)?v.map(x=>typeof x==='object'&&x?JSON.stringify(x):String(x||'')).join(' '):v&&typeof v==='object'?JSON.stringify(v):String(v||'')).join(' ').replace(/\s+/g,' ').trim();return text.length>=80};
function loginView(message=''){root.innerHTML='<section class="admin-auth card"><div class="eyebrow">OWNER AUDIT</div><h1>Content Audit Workbench</h1><p>Review the learner content, see the automated quality audit, and record your expert review. Review status never controls whether existing content is visible to learners.</p><label class="admin-field"><span>GitHub token</span><input id="adminToken" type="password" autocomplete="off" placeholder="github_pat_…"></label><button class="btn primary" id="adminLogin">SIGN IN →</button><p class="admin-help">The GitHub account must be <b>ankitvrsharma</b> and the token needs repository Contents read/write access.</p>'+(message?'<div class="admin-error" role="alert">'+esc(message)+'</div>':'')+'</section>';document.querySelector('#adminLogin').onclick=login}
async function login(){const input=document.querySelector('#adminToken'),v=input?.value.trim();if(!v)return loginView('Enter your GitHub token.');token=v;try{const me=await api('/user');if(me.login!==OWNER)throw new Error('This GitHub account is not the site owner.');sessionStorage.setItem(KEY,token);sessionStorage.setItem(AUTH,'1');await dashboard()}catch(e){sessionStorage.removeItem(KEY);token='';loginView(e.message||'Sign-in failed.');}}
async function loadAuditState(){const r=await fetch('./content-audit.json?v=20261006-audit-status-v1',{cache:'no-store'});if(r.ok)auditState=await r.json()}
function titleFor(type,id){if(type==='microtopics'){const [u,t,m]=String(id).split('-').map(Number),unit=data?.units?.find(x=>x.id===u),topic=unit?.topics?.find(x=>x.id===t),micro=topic?.microtopics?.find(x=>x.id===m);return micro?unit.title+' · '+topic.title+' · '+micro.title:id}const q=questions.find(x=>String(x.id)===String(id));return q?.question||id}
function hrefFor(type,id){if(type==='microtopics'){const [u,t,m]=String(id).split('-');return 'microtopic.html?unit='+encodeURIComponent(u)+'&topic='+encodeURIComponent(t)+'&micro='+encodeURIComponent(m)}return 'practice.html'}
function makeItem(type,id,audit){const st=status(type,id,audit),action=st==='EXPERT REVIEWED'?'<button class="btn admin-return" data-type="'+type+'" data-id="'+esc(id)+'">RETURN TO NEED REVIEW</button>':'<button class="btn primary admin-expert" data-type="'+type+'" data-id="'+esc(id)+'">MARK EXPERT REVIEWED</button>';return '<article class="admin-item"><div class="admin-item-copy"><span class="admin-status '+st.toLowerCase().replace(/\s+/g,'-')+'">'+esc(st)+'</span><h3>'+esc(titleFor(type,id))+'</h3><p>Audit score: <b>'+audit.score+'</b> · '+esc((audit.issues||[]).join(', ')||'No audit issues')+'</p></div><div class="admin-actions"><a class="btn" href="'+hrefFor(type,id)+'">OPEN</a>'+action+'</div></article>'}
function rowsFor(){const ctx={get data(){return data},get questions(){return questions}},audit=window.NETPsychologyContentAudit.create(ctx).expertAudit;const micros=(data?.units||[]).flatMap(u=>(u.topics||[]).flatMap(t=>(t.microtopics||[]).filter(hasContent).map(m=>({type:'microtopics',id:String(u.id)+'-'+String(t.id)+'-'+String(m.id)}))));const qs=(questions||[]).map(q=>({type:'questions',id:String(q.id)}));return [...micros,...qs].map(x=>({x,a:audit(x.type,x.id),st:status(x.type,x.id,audit(x.type,x.id))})).filter(r=>filter==='ALL'||r.st===filter).sort((a,b)=>a.a.score-b.a.score)}
function renderQueue(){const ctx={get data(){return data},get questions(){return questions}},audit=window.NETPsychologyContentAudit.create(ctx).expertAudit,all=rowsFor(),counts=['ALL','NEED REVIEW','REVIEWED','EXPERT REVIEWED'].map(x=>[x,rowsFor().filter(r=>x==='ALL'||r.st===x).length]);root.querySelector('#adminQueue').innerHTML='<section class="admin-toolbar card"><div><strong>'+counts.find(x=>x[0]==='ALL')[1]+'</strong><span>content items</span></div><div><strong>'+counts.find(x=>x[0]==='NEED REVIEW')[1]+'</strong><span>need your review</span></div><div><strong>'+counts.find(x=>x[0]==='EXPERT REVIEWED')[1]+'</strong><span>expert reviewed</span></div><button class="btn" id="adminLogout">SIGN OUT</button></section><div class="admin-filters">'+['ALL','NEED REVIEW','REVIEWED','EXPERT REVIEWED'].map(x=>'<button class="admin-filter '+(filter===x?'active':'')+'" data-filter="'+x+'">'+x+'</button>').join('')+'</div>'+(all.length?all.map(r=>makeItem(r.x.type,r.x.id,r.a)).join(''):'<section class="card admin-empty"><h2>No items in this view</h2><p>Change the filter to see another review state.</p></section>');root.querySelector('#adminLogout').onclick=logout;root.querySelectorAll('.admin-filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderQueue()});root.querySelectorAll('.admin-expert').forEach(b=>b.onclick=()=>changeReview(b.dataset.type,b.dataset.id,true));root.querySelectorAll('.admin-return').forEach(b=>b.onclick=()=>changeReview(b.dataset.type,b.dataset.id,false))}
async function changeReview(type,id,expertReviewed){const key=String(id),next=new Set(ids(type));expertReviewed?next.add(key):next.delete(key);auditState.expert_reviewed[type]=Array.from(next).sort();auditState.updated_at=new Date().toISOString();try{const file=await api('/repos/'+REPO+'/contents/content-audit.json?ref='+encodeURIComponent(BRANCH));const body=btoa(unescape(encodeURIComponent(JSON.stringify(auditState,null,2)+'\n')));await api('/repos/'+REPO+'/contents/content-audit.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:(expertReviewed?'Admin: mark expert reviewed ':'Admin: return to need review ')+type+' '+id,content:body,sha:file.sha,branch:BRANCH})});await loadAuditState();renderQueue()}catch(e){alert('Could not save the review status: '+e.message)}}
function logout(){sessionStorage.removeItem(KEY);sessionStorage.removeItem(AUTH);token='';loginView()}
async function dashboard(){root.innerHTML='<section class="admin-hero"><div class="eyebrow">OWNER AUDIT</div><h1>Content Audit Workbench</h1><p>Every content item remains visible when content exists. Review labels describe the quality-review state, not publication access.</p></section><div id="adminQueue" class="admin-queue"><div class="card">Loading content…</div></div>';try{await Promise.all([loadAuditState(),loadJSON('data.json'),loadJSON('practice_questions.json')]);renderQueue()}catch(e){root.innerHTML='<section class="card"><h2>Could not load audit data</h2><p>'+esc(e.message)+'</p><button class="btn" id="adminLogout">SIGN OUT</button></section>';document.querySelector('#adminLogout').onclick=logout}}
async function start(){if(!token)return loginView();try{const me=await api('/user');if(me.login!==OWNER)throw new Error('Owner account required.');await dashboard()}catch(e){logout()}}
start();
})();