(()=>{'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const KEY='netPsychOwnerContentQA';
let audit=null,rows=[];
const store=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const save=x=>{try{localStorage.setItem(KEY,JSON.stringify(x))}catch{}};
const statusFor=(type,id)=>{const s=store();if((s.rejected?.[type]||[]).includes(id))return'REJECTED';if((s.approved?.[type]||[]).includes(id))return'APPROVED';return'AUTO';};
function setStatus(type,id,status){const s=store();s.approved=s.approved||{};s.rejected=s.rejected||{};for(const k of ['approved','rejected'])s[k][type]=(s[k][type]||[]).filter(x=>x!==id);if(status==='APPROVED')s.approved[type].push(id);if(status==='REJECTED')s.rejected[type].push(id);save(s);render();}
async function get(path){const r=await fetch('./'+path+'?v=20261004-audit1');if(!r.ok)throw Error(path+' '+r.status);return r.json()}
function coreAudit(data,qs,map,ex){
 const mids=new Set(data.units.flatMap(u=>u.topics.flatMap(t=>t.microtopics.map(m=>`${u.id}-${t.id}-${m.id}`))));
 const ov=map.question_overrides||{},out={questions:[],microtopics:[],quickLearnCards:[],activeRecall:[]};
 for(const q of qs){let [u,t,m]=[q.unit,q.topic,q.micro];if(ov[q.id]?.target)[u,t,m]=ov[q.id].target.split('-').map(Number);const issues=[];if(!q.id||!String(q.question||'').trim())issues.push('missing_question');if(!Array.isArray(q.options)||q.options.length!==4)issues.push('options');if(Array.isArray(q.options)&&new Set(q.options.map(x=>String(x).trim().toLowerCase())).size!==q.options.length)issues.push('duplicate_options');if(!Number.isInteger(q.answer)||q.answer<0||q.answer>=4)issues.push('answer');if(u==null||t==null||m==null)issues.push('unmapped');else if(!mids.has(`${u}-${t}-${m}`))issues.push('broken_mapping');if(!String(q.explanation||ex[q.id]||'').trim())issues.push('missing_explanation');out.questions.push({id:q.id,title:q.question,issues,micro:u!=null?`${u}-${t}-${m}`:''});}
 for(const u of data.units)for(const t of u.topics)for(const m of t.microtopics){const id=`${u.id}-${t.id}-${m.id}`,issues=[];if(!String(m.expert_explanation||m.detailed_explanation||m.content_notes||'').trim())issues.push('missing_explanation');if(!String(m.content_notes||'').trim())issues.push('missing_notes');if(!Array.isArray(m.sources)||!m.sources.length)issues.push('missing_sources');out.microtopics.push({id,title:m.title,issues});for(const angle of ['CORE IDEA','KEY FEATURES','PYQ FOCUS','EXAM TRAP','SOURCE DETAIL','RECALL CUE','CONNECTION'])out.quickLearnCards.push({id:id+'|'+angle,title:m.title+' — '+angle,issues:issues.slice()});}
 out.activeRecall=out.questions.map(x=>({id:x.id,title:x.title,issues:x.issues.slice()}));return out;
}
function render(){if(!audit)return;const q=audit.questions,m=audit.microtopics,ql=audit.quickLearnCards,r=audit.activeRecall;const cards=[['Questions',q],['Micro-topic explanations',m],['Quick Learn Cards',ql],['Active Recall exercises',r]];$('#summary').innerHTML=cards.map(([n,a])=>{const pass=a.filter(x=>!x.issues.length).length;return `<article class="qa-stat"><span>${esc(n)}</span><strong>${pass}/${a.length}</strong><small>${Math.round(pass/a.length*100)||0}% AI-audit pass</small></article>`}).join('');const total=cards.reduce((n,[,a])=>n+a.length,0),blocked=cards.reduce((n,[,a])=>n+a.filter(x=>x.issues.length).length,0);$('#gate').innerHTML=`<div class="qa-gate"><b>Current publishing mode: AI PASS + OWNER APPROVED</b><span>${total-blocked} items pass the current automated gate; ${blocked} are held for review.</span></div>`;rows=[...q.map(x=>({...x,type:'questions',pool:'Question Pool'})),...m.map(x=>({...x,type:'microtopics',pool:'Micro-topic Explanation Pool'})),...ql.map(x=>({...x,type:'quickLearnCards',pool:'Quick Learn Card Pool'})),...r.map(x=>({...x,type:'activeRecall',pool:'Active Recall Pool'}))];filterRows();}
function filterRows(){const term=($('#search').value||'').toLowerCase(),filter=$('#filter').value;const view=rows.filter(x=>(filter==='all'||(filter==='issues'&&x.issues.length)|| (filter==='auto'&&!x.issues.length)|| (filter==='approved'&&statusFor(x.type,x.id)==='APPROVED')||(filter==='rejected'&&statusFor(x.type,x.id)==='REJECTED'))&&(!term||String(x.id+' '+x.title+' '+x.pool).toLowerCase().includes(term))).slice(0,250);$('#rows').innerHTML=view.length?view.map(x=>{const s=statusFor(x.type,x.id),ai=x.issues.length?'REVIEW':'PASS';return `<article class="qa-row"><div><small>${esc(x.pool)}</small><h3>${esc(x.title||x.id)}</h3><code>${esc(x.id)}</code><p class="qa-issues">${x.issues.length?x.issues.join(' · '):'No blocking automated issues'}</p></div><div class="qa-actions"><span class="pill ${s.toLowerCase()}">${s}</span><span class="pill ${ai.toLowerCase()}">AI ${ai}</span><button data-set="APPROVED" data-type="${esc(x.type)}" data-id="${esc(x.id)}">Approve</button><button data-set="REJECTED" data-type="${esc(x.type)}" data-id="${esc(x.id)}">Reject</button><button data-set="AUTO" data-type="${esc(x.type)}" data-id="${esc(x.id)}">Clear</button></div></article>`}).join(''):'<div class="empty">No matching audit items.</div>';$('#count').textContent=view.length+' shown';}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
async function boot(){try{const [d,q,e,map]=await Promise.all([get('data.json'),get('practice_questions.json'),get('practice_explanations.json'),get('mcq_mapping.json')]);audit=coreAudit(d,q,map,e);render();}catch(e){$('#rows').innerHTML='<div class="empty">Audit could not load: '+esc(e.message)+'</div>';}}
document.addEventListener('click',e=>{const b=e.target.closest('button[data-set]');if(b){setStatus(b.dataset.type,b.dataset.id,b.dataset.set);return}if(e.target.closest('#export')){const s=store();download('content-owner-overrides.json',{schema_version:1,owner_approved:s.approved||{},owner_rejected:s.rejected||{},notes:{},updated_at:new Date().toISOString()});}if(e.target.closest('#export-report')){download('content-audit-report.json',{generated_at:new Date().toISOString(),audit});}});
$('#search').addEventListener('input',filterRows);$('#filter').addEventListener('change',filterRows);boot();
})();