(function(){'use strict';
const REF='ncndgskqkczfurfiycng';
const SUPABASE_URL='https://'+REF+'.supabase.co';
const KEY=(window.NETPSY_SUPABASE_CONFIG&&window.NETPSY_SUPABASE_CONFIG.publishableKey)||'';
const SESSION_KEY='netPsychSupabaseSession',STATE_KEY='netPsychProgress';
let session=null,user=null,profile=null,syncTimer=null;
const headers=token=>({apikey:KEY,Authorization:'Bearer '+(token||KEY),'Content-Type':'application/json'});
async function request(path,options={}){const token=options.token||session?.access_token;if(!token&&!path.startsWith('/auth/v1/signup')&&!path.startsWith('/auth/v1/token')&&!path.startsWith('/auth/v1/resend'))throw new Error('Not signed in');const r=await fetch(SUPABASE_URL+path,{...options,headers:{...headers(token),...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||'Supabase request failed ('+r.status+')');return data}
async function loadProfile(){if(!user?.id)return null;try{const rows=await request('/rest/v1/profiles?select=id,email,display_name,role&id=eq.'+encodeURIComponent(user.id)+'&limit=1');return rows?.[0]||null}catch{return null}}
async function loadSession(){try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;session=JSON.parse(raw);if(!session?.access_token)throw new Error('No session');try{user=await request('/auth/v1/user')}catch{if(!session.refresh_token)throw new Error('Session expired');session=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY},body:JSON.stringify({refresh_token:session.refresh_token})});localStorage.setItem(SESSION_KEY,JSON.stringify(session));user=await request('/auth/v1/user')}profile=await loadProfile();return session}catch{localStorage.removeItem(SESSION_KEY);session=user=profile=null;return null}}
async function loadRemoteState(){if(!user?.id)return null;try{const rows=await request('/rest/v1/learning_state?select=state,updated_at&user_id=eq.'+encodeURIComponent(user.id)+'&limit=1');return rows?.[0]?.state||null}catch{return null}}
async function syncState(){if(!user?.id)return false;try{let state={};try{state=JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch{}await request('/rest/v1/learning_state?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:user.id,state,updated_at:new Date().toISOString()})});return true}catch{return false}}
function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(syncState,1000)}
function installPersistence(){if(Storage.prototype.__netPsyWrapped)return;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){const result=original.call(this,k,v);if(this===localStorage&&k===STATE_KEY&&user)scheduleSync();return result}}
async function ensureState(){const remote=await loadRemoteState();let local=null;try{local=JSON.parse(localStorage.getItem(STATE_KEY)||'null')}catch{}if(remote&&typeof remote==='object'){const merged={...(remote||{}),...(local||{})};if(Array.isArray(remote._practiceHistory)||Array.isArray(local?._practiceHistory)){const seen=new Set(),history=[];for(const item of [...(remote._practiceHistory||[]),...(local?._practiceHistory||[])]){const id=JSON.stringify(item);if(!seen.has(id)){seen.add(id);history.push(item)}}merged._practiceHistory=history}localStorage.setItem(STATE_KEY,JSON.stringify(merged));if(JSON.stringify(merged)!==JSON.stringify(remote))await syncState()}else if(local&&Object.keys(local).length)await syncState()}
async function signUp(email,password,displayName=''){const redirectTo=new URL('login.html?confirmed=1',window.location.href).href;const data=await request('/auth/v1/signup',{method:'POST',headers:{apikey:KEY},body:JSON.stringify({email,password,data:{display_name:displayName},options:{email_redirect_to:redirectTo}})});if(data?.access_token){session=data;user=data.user;localStorage.setItem(SESSION_KEY,JSON.stringify(session));profile=await loadProfile();await ensureState()}return data}
async function resendConfirmation(email){const redirectTo=new URL('login.html?confirmed=1',window.location.href).href;return request('/auth/v1/resend',{method:'POST',headers:{apikey:KEY},body:JSON.stringify({type:'signup',email,options:{email_redirect_to:redirectTo}})})}
async function signIn(email,password){const data=await request('/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY},body:JSON.stringify({email,password})});session=data;user=data.user;localStorage.setItem(SESSION_KEY,JSON.stringify(session));profile=await loadProfile();await ensureState();return{user,profile}}
async function signOut(){try{if(session?.access_token)await request('/auth/v1/logout',{method:'POST'})}catch{}localStorage.removeItem(SESSION_KEY);session=user=profile=null}
async function init(){installPersistence();if(!KEY)return null;await loadSession();if(user)await ensureState();return{user,profile}}
window.NETPSY_AUTH={ready:init(),signUp,signIn,resendConfirmation,signOut,syncState,isAdmin:()=>profile?.role==='admin',getUser:()=>user,getProfile:()=>profile,getSession:()=>session,config:{url:SUPABASE_URL,ref:REF}};
})();
